x-healthcheck: &healthcheck
  interval: 30s
  timeout: 5s
  retries: 15
  start_period: 3s
  start_interval: 1s

networks:
  postgres:

volumes:
  postgres:

services:
  postgres:
    image: supabase/postgres:17.6.1.072
    restart: unless-stopped
    networks:
      postgres:
        aliases:
          - pg.lokal
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD

      # Required for healthcheck
      - PGPASSWORD=${POSTGRES_PASSWORD:?}
    volumes:
      - postgres:/var/lib/postgresql/data
    healthcheck:
      <<: *healthcheck
      test: [CMD-SHELL, pg_isready -U "$$POSTGRES_USER" -d "$$POSTGRES_DB"]
